### PR TITLE
FP-15, FP-22, FP-12  Create the level 1 game page, Figure out game mechanic for level 1, Created the store page

### PR DESCRIPTION
**Pull request by Nicklozoya**
Added a store with a donation button on the store component. Added a background image and cat gif on the level1 component. Worked on mechanics to transition user towards level two on the level1 component.

### CODE REVIEW

**Review by loyaltyjones — APPROVED** [review]
Looks awesome!

**Review by itsGoodJuJu — CHANGES_REQUESTED** [review]
Please update the organization of the code. Make sure nested element appear nested (indented). Once you update that, everything should be good to go! Thank you.

**Review by Hoang-J — CHANGES_REQUESTED** [review]
Looks really nice Nick, love the pictures! Just one thing, can you organize the code a bit with indentations to make it look cleaner please? But overall, great job!

**Review by Hoang-J — APPROVED** [review]
Looks good Nick! Great work

**Review by itsGoodJuJu — APPROVED** [review]
Looks much cleaner! This is approved to merge.

**Pull request merged**
